"""Demo catalog: 7 categories × 25 real, publicly known items.

Descriptions are short summaries written for this project. Themes overlap
on purpose (AI, space, psychology, programming, design, business…) so
cross-category recommendations visibly work in a demo.
Rows: (title, description, tags, rating). Movies/Games are rated out of 10,
everything else out of 5 — the engine normalises per category.
"""

MOVIES = [
    ("Inception", "A thief who steals secrets through shared dreams is hired to plant an idea in a target's mind, descending through layered dream worlds.", "sci-fi, thriller, dreams, mind-bending, heist", 8.8),
    ("Interstellar", "Astronauts travel through a wormhole near Saturn searching for a new home for humanity as Earth's crops fail.", "space, sci-fi, physics, black holes, family, science", 8.7),
    ("The Social Network", "The story of how Facebook was founded at Harvard and the lawsuits and broken friendships that followed.", "drama, startups, programming, business, technology", 7.8),
    ("Ex Machina", "A young programmer is invited to evaluate whether a humanoid robot built by a reclusive CEO truly has consciousness.", "ai, artificial intelligence, robots, sci-fi, ethics, psychology", 7.7),
    ("Her", "A lonely writer develops a relationship with an operating system powered by an emotionally intelligent AI.", "ai, romance, artificial intelligence, drama, loneliness, psychology", 8.0),
    ("The Imitation Game", "Alan Turing and a team of codebreakers race to crack the German Enigma code during World War II.", "history, mathematics, computing, codebreaking, biography, war", 8.0),
    ("Hidden Figures", "Three Black women mathematicians at NASA play crucial roles in launching astronaut John Glenn into orbit.", "space, nasa, mathematics, history, biography, science", 7.8),
    ("The Martian", "An astronaut stranded on Mars uses botany, engineering and humor to survive until a rescue can arrive.", "space, survival, science, engineering, sci-fi, mars", 8.0),
    ("Good Will Hunting", "A janitor at MIT with a gift for mathematics works with a therapist to confront his past.", "drama, mathematics, psychology, therapy, friendship", 8.3),
    ("Inside Out", "The emotions inside a young girl's mind — Joy, Sadness, Anger, Fear and Disgust — guide her through a big move.", "animation, psychology, emotions, family, mind", 8.1),
    ("The Matrix", "A hacker discovers that reality is a simulation run by machines and joins a rebellion to free humanity.", "sci-fi, ai, hacking, action, simulation, philosophy", 8.7),
    ("Moneyball", "A baseball manager uses data analysis and statistics to build a winning team on a tiny budget.", "sports, data science, statistics, business, analytics", 7.6),
    ("A Beautiful Mind", "The life of mathematician John Nash, his breakthroughs in game theory and his struggle with schizophrenia.", "biography, mathematics, psychology, drama, game theory", 8.2),
    ("Gravity", "Two astronauts are stranded in orbit after debris destroys their space shuttle.", "space, survival, thriller, sci-fi", 7.7),
    ("Arrival", "A linguist works to communicate with mysterious alien visitors whose language changes how she perceives time.", "sci-fi, language, linguistics, aliens, mind-bending", 7.9),
    ("WALL-E", "A small trash-compacting robot left on an abandoned Earth falls in love and follows a probe into space.", "animation, robots, space, environment, family, ai", 8.4),
    ("Steve Jobs", "Behind the scenes of three product launches that defined Apple co-founder Steve Jobs.", "biography, technology, business, design, startups", 7.2),
    ("The Pursuit of Happyness", "A struggling salesman and his son face homelessness while he competes for a stockbroker internship.", "drama, biography, business, motivation, family", 8.0),
    ("Whiplash", "A young jazz drummer is pushed to his limits by a ruthless music instructor.", "music, drama, ambition, jazz, psychology", 8.5),
    ("Ford v Ferrari", "Engineers and a driver set out to build a Ford race car capable of beating Ferrari at Le Mans.", "sports, engineering, racing, cars, biography", 8.1),
    ("Spider-Man: Into the Spider-Verse", "Teenager Miles Morales becomes Spider-Man and meets heroes from other dimensions in a groundbreaking animated style.", "animation, superhero, action, art, design", 8.4),
    ("The Big Short", "A few investors predict the 2008 housing collapse and bet against the banks.", "finance, business, economics, drama, biography", 7.8),
    ("Apollo 13", "NASA engineers and astronauts improvise to bring a damaged spacecraft safely back to Earth.", "space, nasa, engineering, history, survival", 7.7),
    ("Ratatouille", "A rat with a talent for cooking teams up with a young kitchen worker in a Paris restaurant.", "animation, cooking, food, family, dreams", 8.1),
    ("Chef", "A chef quits his restaurant job and starts a food truck, rediscovering his love of cooking.", "cooking, food, comedy, family, road trip", 7.3),
    ("Blade Runner 2049", "A replicant officer uncovers a secret that could change the balance between humans and artificial beings.", "sci-fi, ai, robots, dystopia, mystery", 8.0),
]

BOOKS = [
    ("Python Crash Course", "A hands-on introduction to Python programming that ends with games, data visualisations and web apps.", "python, programming, beginners, coding, projects", 4.7),
    ("Automate the Boring Stuff with Python", "Teaches practical Python for automating everyday tasks like files, spreadsheets and web scraping.", "python, programming, automation, productivity, beginners", 4.7),
    ("Clean Code", "Principles and practices for writing readable, maintainable software.", "programming, software engineering, best practices, coding", 4.4),
    ("The Pragmatic Programmer", "Timeless advice on craftsmanship, career and practical habits for software developers.", "programming, software engineering, career, coding", 4.6),
    ("Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow", "A practical guide to building machine learning and deep learning systems in Python.", "machine learning, ai, python, deep learning, data science", 4.7),
    ("Life 3.0", "Explores how artificial intelligence may reshape work, war, justice and what it means to be human.", "ai, artificial intelligence, future, ethics, technology", 4.2),
    ("Superintelligence", "Examines the risks and strategies around machines that could surpass human intelligence.", "ai, artificial intelligence, philosophy, future, risk", 3.9),
    ("Thinking, Fast and Slow", "A Nobel laureate explains the two systems of thought that drive our judgments and biases.", "psychology, decision making, behavioral economics, mind", 4.2),
    ("Atomic Habits", "A practical framework for building good habits and breaking bad ones through small changes.", "self-help, habits, psychology, productivity", 4.4),
    ("Sapiens", "A brief history of humankind from early humans to the modern age of science and capitalism.", "history, anthropology, society, science", 4.4),
    ("A Brief History of Time", "Stephen Hawking explains black holes, the Big Bang and the nature of time for general readers.", "space, physics, cosmology, science, black holes", 4.2),
    ("Cosmos", "Carl Sagan's journey through the universe, science history and humanity's place among the stars.", "space, astronomy, science, history", 4.4),
    ("The Martian (Novel)", "An astronaut stranded on Mars survives using science, ingenuity and a sense of humour.", "space, sci-fi, survival, science, mars", 4.4),
    ("Dune", "On a desert planet, a young noble navigates politics, prophecy and ecology in an epic struggle.", "sci-fi, fantasy, politics, ecology, classic", 4.3),
    ("Project Hail Mary", "A lone astronaut wakes up with no memory and must save Earth from a dying sun.", "space, sci-fi, science, friendship, survival", 4.5),
    ("1984", "A classic dystopia about surveillance, propaganda and a totalitarian state.", "classic, dystopia, politics, fiction", 4.2),
    ("Man's Search for Meaning", "A psychiatrist reflects on surviving concentration camps and finding purpose through suffering.", "psychology, philosophy, meaning, history, memoir", 4.4),
    ("Influence: The Psychology of Persuasion", "Explains six principles of persuasion and how they shape what people say yes to.", "psychology, persuasion, marketing, business", 4.3),
    ("The Design of Everyday Things", "Why some products are a joy to use and others frustrate — the foundations of user-centred design.", "design, ux, psychology, usability, product", 4.2),
    ("Don't Make Me Think", "A short, friendly guide to web usability and intuitive interface design.", "design, ux, web, usability", 4.3),
    ("Zero to One", "Notes on startups and how to build companies that create something genuinely new.", "business, startups, entrepreneurship, technology", 4.2),
    ("The Lean Startup", "A method for building startups through fast experiments, feedback and iteration.", "business, startups, entrepreneurship, product", 4.1),
    ("Steve Jobs (Biography)", "Walter Isaacson's biography of Apple's co-founder based on many interviews.", "biography, technology, business, design", 4.2),
    ("Salt, Fat, Acid, Heat", "Teaches the four elements of good cooking so you can cook without recipes.", "cooking, food, recipes, kitchen", 4.6),
    ("Kitchen Confidential", "A chef's candid, funny memoir about life behind restaurant kitchen doors.", "cooking, food, memoir, restaurants", 4.1),
]

COURSES = [
    ("Python for Everybody", "University of Michigan's beginner course covering Python basics, data structures and web data.", "python, programming, beginners, data", 4.8),
    ("CS50's Introduction to Computer Science", "Harvard's famous intro to computer science covering C, Python, SQL and web development.", "programming, computer science, python, beginners, web", 4.9),
    ("Machine Learning Specialization", "Andrew Ng's course on supervised learning, neural networks and recommender systems.", "machine learning, ai, python, neural networks, recommender systems", 4.9),
    ("Deep Learning Specialization", "Build and train deep neural networks, CNNs and sequence models.", "deep learning, ai, neural networks, python, machine learning", 4.8),
    ("AI For Everyone", "A non-technical overview of what AI can and cannot do and how to use it in organisations.", "ai, artificial intelligence, business, beginners, strategy", 4.8),
    ("Elements of AI", "A free online course introducing the basics of artificial intelligence to everyone.", "ai, artificial intelligence, beginners, ethics", 4.7),
    ("Google Data Analytics Certificate", "Learn spreadsheets, SQL, R and Tableau to start a career in data analytics.", "data analytics, sql, data science, career, spreadsheets", 4.8),
    ("Learning How to Learn", "Practical techniques from neuroscience and psychology to learn more effectively.", "psychology, learning, study skills, neuroscience", 4.8),
    ("The Science of Well-Being", "Yale's popular course on the psychology of happiness and building better habits.", "psychology, happiness, habits, wellbeing", 4.9),
    ("Introduction to Psychology", "A broad survey of how the mind works: perception, memory, emotion and behaviour.", "psychology, mind, behaviour, science", 4.8),
    ("Google UX Design Certificate", "Learn the UX design process, wireframing, prototyping and Figma.", "design, ux, figma, prototyping, career", 4.8),
    ("Graphic Design Specialization", "CalArts course on typography, imagemaking and visual composition.", "design, graphic design, typography, art", 4.7),
    ("Full Stack Open", "University of Helsinki's free course on modern web development with React, Node and GraphQL.", "web development, javascript, react, programming", 4.8),
    ("The Odin Project", "A free open-source curriculum for becoming a full-stack web developer.", "web development, javascript, programming, beginners", 4.8),
    ("Intro to SQL (Kaggle)", "Short hands-on lessons on querying data with SQL and BigQuery.", "sql, data science, databases, beginners", 4.6),
    ("Astronomy: Exploring Time and Space", "University of Arizona's tour of planets, stars, galaxies and the search for life.", "space, astronomy, science, physics", 4.8),
    ("Financial Markets", "Yale's Robert Shiller explains risk, insurance, banking and behavioural finance.", "finance, business, economics, investing", 4.8),
    ("Introduction to Game Development", "Learn game design fundamentals and build games with Unity and C#.", "gaming, game development, unity, programming", 4.6),
    ("Music Production Specialization", "Berklee's course on recording, mixing and producing music in a DAW.", "music, production, audio, creativity", 4.7),
    ("Entrepreneurship Specialization", "Wharton's course on developing ideas, launching ventures and growing a business.", "business, entrepreneurship, startups, strategy", 4.6),
    ("Cybersecurity Fundamentals", "Core concepts of security threats, cryptography, networks and defence.", "cybersecurity, security, networks, technology", 4.6),
    ("Introduction to Cloud Computing", "Learn cloud models, services and the basics of AWS, Azure and Google Cloud.", "cloud, technology, aws, career", 4.6),
    ("Natural Language Processing Specialization", "Build models for sentiment, translation and question answering with deep learning.", "nlp, ai, machine learning, deep learning, python", 4.6),
    ("Cooking for Busy Healthy People", "Simple, healthy home cooking techniques for people short on time.", "cooking, food, health, nutrition", 4.7),
    ("Chocolate Making Basics", "Learn the science and craft of tempering, ganache and chocolate desserts.", "cooking, baking, food, desserts", 4.5),
]

JOBS = [
    ("Machine Learning Engineer", "Design, train and deploy machine learning models into production systems using Python.", "machine learning, ai, python, deep learning, mlops", 4.6),
    ("Data Scientist", "Analyse data, build predictive models and communicate insights that guide decisions.", "data science, python, statistics, machine learning, sql", 4.5),
    ("AI Research Scientist", "Invent new AI methods, run experiments and publish findings on neural networks.", "ai, research, deep learning, mathematics, neural networks", 4.6),
    ("Python Developer", "Build backend services, APIs and automation tools in Python.", "python, programming, backend, apis", 4.4),
    ("Frontend Developer", "Build fast, accessible user interfaces with HTML, CSS and JavaScript frameworks.", "web development, javascript, react, frontend, design", 4.3),
    ("Full Stack Developer", "Work across the database, server and browser to ship complete web products.", "web development, javascript, python, databases, programming", 4.4),
    ("Data Analyst", "Turn raw data into dashboards and reports using SQL, spreadsheets and visualisation tools.", "data analytics, sql, spreadsheets, business, statistics", 4.3),
    ("Prompt Engineer", "Design and evaluate prompts and workflows that get reliable results from AI models.", "ai, nlp, language models, writing", 4.2),
    ("UX Designer", "Research user needs and design intuitive flows, wireframes and prototypes.", "design, ux, research, figma, psychology", 4.4),
    ("Product Designer", "Shape the look, feel and usability of digital products end to end.", "design, ux, product, figma", 4.4),
    ("Product Manager", "Decide what to build, coordinate teams and own product outcomes.", "business, product, strategy, startups", 4.3),
    ("Clinical Psychologist", "Assess and treat mental health conditions through therapy and evidence-based care.", "psychology, therapy, health, research", 4.4),
    ("School Counselor", "Support students' academic, career and emotional development.", "psychology, education, counseling, students", 4.3),
    ("Aerospace Engineer", "Design and test aircraft, spacecraft and satellite systems.", "space, engineering, physics, aerospace", 4.5),
    ("Astronomer", "Study stars, planets and galaxies using telescopes, data and physics.", "space, astronomy, research, physics, data science", 4.4),
    ("Game Developer", "Program gameplay systems, tools and engines for video games.", "gaming, game development, programming, c++, unity", 4.2),
    ("Game Designer", "Create game mechanics, levels and player experiences.", "gaming, design, creativity, storytelling", 4.2),
    ("Cybersecurity Analyst", "Monitor systems, investigate incidents and protect organisations from attacks.", "cybersecurity, security, networks, technology", 4.4),
    ("Cloud Engineer", "Build and run scalable infrastructure on cloud platforms.", "cloud, aws, devops, technology", 4.4),
    ("DevOps Engineer", "Automate builds, deployments and monitoring for reliable software delivery.", "devops, cloud, automation, programming", 4.3),
    ("Music Producer", "Record, arrange, mix and produce tracks for artists and media.", "music, production, audio, creativity", 4.1),
    ("Digital Marketing Specialist", "Plan campaigns across search, social and email and measure what works.", "marketing, business, analytics, social media", 4.1),
    ("Financial Analyst", "Model company performance and advise on investments and budgets.", "finance, business, spreadsheets, economics", 4.2),
    ("Science Teacher", "Teach physics, chemistry and biology and inspire curiosity in students.", "education, science, teaching, students", 4.5),
    ("Chef de Partie", "Run a section of a professional kitchen and prepare dishes to a high standard.", "cooking, food, restaurants, kitchen", 4.0),
]

APPS = [
    ("Duolingo", "Learn languages through short, game-like daily lessons.", "learning, languages, education, gamification", 4.7),
    ("Khan Academy", "Free lessons and practice in maths, science, computing and more.", "learning, education, mathematics, science", 4.8),
    ("Notion", "An all-in-one workspace for notes, docs, tasks and wikis.", "productivity, notes, organisation, planning", 4.7),
    ("Anki", "Flashcards with spaced repetition to remember anything long-term.", "learning, memory, study skills, psychology", 4.6),
    ("Forest", "Stay focused by growing virtual trees while you keep your phone down.", "productivity, focus, habits, study skills", 4.8),
    ("Headspace", "Guided meditation and mindfulness for stress, sleep and focus.", "wellbeing, meditation, psychology, health", 4.8),
    ("Brilliant", "Interactive lessons in maths, science and computer science.", "learning, mathematics, science, programming", 4.7),
    ("Sololearn", "Learn to code in Python, JavaScript and more in bite-sized lessons.", "programming, python, learning, coding, beginners", 4.7),
    ("Mimo", "Practise coding and web development on your phone with interactive exercises.", "programming, web development, coding, learning", 4.7),
    ("Grasshopper", "A beginner-friendly app for learning JavaScript through puzzles.", "programming, javascript, coding, beginners", 4.6),
    ("ChatGPT", "An AI assistant that answers questions, writes and helps with code.", "ai, artificial intelligence, chatbot, productivity, writing", 4.8),
    ("Claude", "An AI assistant for writing, analysis, coding and learning.", "ai, artificial intelligence, chatbot, writing, programming", 4.7),
    ("Google Lens", "Search what you see: identify objects, translate text and solve homework with the camera.", "ai, computer vision, search, learning", 4.6),
    ("Star Walk 2", "Point your phone at the sky to identify stars, planets and constellations.", "space, astronomy, augmented reality, science", 4.7),
    ("NASA App", "Images, videos, mission news and live streams from NASA.", "space, nasa, science, news", 4.6),
    ("Figma", "Collaborative interface design and prototyping in the browser.", "design, ux, prototyping, collaboration", 4.7),
    ("Canva", "Design posters, presentations and social graphics with templates.", "design, graphic design, presentations, creativity", 4.8),
    ("Procreate", "A powerful drawing and painting app for iPad.", "art, design, drawing, creativity", 4.7),
    ("Spotify", "Stream music and podcasts with personalised recommendations.", "music, podcasts, streaming, recommendations", 4.6),
    ("GarageBand", "Create music with virtual instruments, loops and recording tools.", "music, production, audio, creativity", 4.5),
    ("Photomath", "Scan a maths problem with your camera and see step-by-step solutions.", "mathematics, learning, education, ai", 4.7),
    ("Quizlet", "Study with flashcards, quizzes and learning games.", "learning, study skills, education, flashcards", 4.7),
    ("GitHub Mobile", "Review code, manage issues and pull requests from your phone.", "programming, coding, collaboration, git", 4.6),
    ("Tasty", "Thousands of step-by-step recipe videos for home cooking.", "cooking, food, recipes, video", 4.8),
    ("Yummly", "Personalised recipe recommendations and meal planning.", "cooking, food, recipes, recommendations", 4.6),
]

GAMES = [
    ("Minecraft", "Build, explore and survive in an endless blocky world; redstone even lets you build working computers.", "sandbox, creativity, building, survival, education", 9.0),
    ("Portal 2", "Solve physics-based puzzles with a portal gun in a darkly funny test facility run by an AI.", "puzzle, physics, ai, story, co-op", 9.5),
    ("Kerbal Space Program", "Design rockets and fly missions using realistic orbital physics.", "space, simulation, physics, engineering, science", 9.0),
    ("Outer Wilds", "Explore a solar system stuck in a time loop and uncover the mystery of an ancient civilization.", "space, exploration, mystery, puzzle, science", 9.2),
    ("No Man's Sky", "Explore, build and trade across a procedurally generated universe of planets.", "space, exploration, survival, procedural generation", 8.0),
    ("Stardew Valley", "Restore a farm, befriend villagers and build a cosy life in the countryside.", "farming, simulation, relaxing, cozy, indie", 9.2),
    ("The Legend of Zelda: Breath of the Wild", "Explore a vast open world of Hyrule with total freedom to climb, cook and fight.", "adventure, open world, exploration, puzzle", 9.7),
    ("Celeste", "A precise platformer about climbing a mountain and dealing with anxiety.", "platformer, indie, psychology, mental health, challenging", 9.2),
    ("Detroit: Become Human", "Androids in near-future Detroit begin to question their programming in a branching story.", "ai, robots, story, choices, sci-fi", 8.6),
    ("Human Resource Machine", "Program office workers to solve puzzles — a gentle introduction to how programming works.", "programming, puzzle, coding, education, logic", 8.3),
    ("Baba Is You", "Change the rules of each level by pushing word blocks around.", "puzzle, logic, indie, programming", 9.0),
    ("Factorio", "Build and automate ever-growing factories on an alien planet.", "automation, strategy, engineering, programming, simulation", 9.6),
    ("Civilization VI", "Lead a civilization from the stone age to the space age in turn-based strategy.", "strategy, history, turn-based, science", 8.7),
    ("Cities: Skylines", "Plan and manage a modern city's roads, services and economy.", "simulation, strategy, city building, design", 8.5),
    ("Hades", "Fight your way out of the underworld in a fast roguelike with a rich mythological story.", "action, roguelike, mythology, indie, story", 9.3),
    ("Hollow Knight", "Explore a beautiful, haunting underground insect kingdom in a challenging metroidvania.", "metroidvania, action, indie, exploration, art", 9.4),
    ("Among Us", "Work as a crew while finding the impostors among you through discussion and deduction.", "multiplayer, social deduction, party, psychology", 8.0),
    ("Rocket League", "Play soccer with rocket-powered cars in fast competitive matches.", "sports, multiplayer, competitive, cars", 8.6),
    ("Beat Saber", "Slash blocks to the rhythm of music in virtual reality.", "music, rhythm, vr, fitness", 9.0),
    ("Guitar Hero III", "Play along to rock songs using a guitar-shaped controller.", "music, rhythm, party, rock", 8.5),
    ("Overcooked! 2", "Cooperate in chaotic kitchens to cook and serve orders against the clock.", "cooking, co-op, party, multiplayer, food", 8.4),
    ("Cooking Simulator", "Run a restaurant kitchen and prepare realistic dishes step by step.", "cooking, simulation, food, restaurants", 7.6),
    ("Return of the Obra Dinn", "Deduce the fate of every crew member of a lost ship using logic and observation.", "mystery, puzzle, detective, logic, indie", 9.3),
    ("SpaceChem", "Design reactors that transform molecules in a programming-like puzzle game.", "puzzle, programming, chemistry, science, engineering", 8.8),
    ("Elden Ring", "Explore a vast, dangerous fantasy world full of challenging bosses and secrets.", "action, rpg, open world, fantasy, challenging", 9.5),
]

TECHNOLOGY = [
    ("Python", "A readable, versatile programming language used for web, data science, AI and automation.", "python, programming, data science, ai, automation", 4.8),
    ("JavaScript", "The language of the web, running in every browser and on servers with Node.js.", "javascript, web development, programming, frontend", 4.5),
    ("TensorFlow", "Google's open-source framework for building and deploying machine learning models.", "machine learning, ai, deep learning, python", 4.5),
    ("PyTorch", "A flexible deep learning framework popular in research and production.", "deep learning, ai, machine learning, python, research", 4.7),
    ("scikit-learn", "Simple, efficient tools for classic machine learning in Python, including TF-IDF.", "machine learning, python, data science, ai", 4.7),
    ("pandas", "A Python library for loading, cleaning and analysing tabular data.", "python, data science, data analytics, programming", 4.7),
    ("Large Language Models", "Neural networks trained on huge amounts of text that can write, summarise and reason.", "ai, nlp, deep learning, language models, chatbot", 4.6),
    ("Transformers (Neural Architecture)", "The attention-based neural network design behind modern language and vision AI.", "ai, deep learning, nlp, neural networks, research", 4.6),
    ("Computer Vision", "Techniques that let computers recognise and understand images and video.", "ai, computer vision, deep learning, robotics", 4.5),
    ("Recommender Systems", "Algorithms that suggest movies, products and courses based on content and behaviour.", "recommender systems, machine learning, ai, personalization", 4.6),
    ("React", "A JavaScript library for building interactive user interfaces from components.", "javascript, web development, frontend, react", 4.6),
    ("FastAPI", "A modern, fast Python framework for building APIs with type hints.", "python, apis, backend, web development", 4.8),
    ("PostgreSQL", "A powerful open-source relational database used by Supabase and many others.", "databases, sql, backend, open source", 4.8),
    ("Supabase", "An open-source backend with Postgres, authentication, storage and row level security.", "databases, backend, authentication, sql, open source", 4.6),
    ("Git", "Distributed version control for tracking changes and collaborating on code.", "programming, git, collaboration, tools", 4.7),
    ("Docker", "Package applications into containers that run the same everywhere.", "devops, cloud, containers, backend", 4.6),
    ("Kubernetes", "Orchestrates containers at scale across clusters of machines.", "devops, cloud, containers, infrastructure", 4.4),
    ("Amazon Web Services", "A large cloud platform offering computing, storage and AI services.", "cloud, aws, infrastructure, technology", 4.5),
    ("Raspberry Pi", "A tiny, affordable computer for learning programming, electronics and robotics.", "hardware, programming, python, robotics, education", 4.8),
    ("Arduino", "An open-source microcontroller platform for building interactive electronics.", "hardware, electronics, robotics, programming", 4.7),
    ("Quantum Computing", "Computing that uses qubits and superposition to tackle certain problems faster.", "quantum, physics, research, future, science", 4.3),
    ("Blockchain", "A shared, tamper-resistant ledger that underpins cryptocurrencies and more.", "blockchain, cryptography, finance, decentralization", 3.9),
    ("Virtual Reality", "Headsets that place you inside immersive 3D worlds for games, training and design.", "vr, gaming, design, immersive", 4.3),
    ("Unity Engine", "A popular engine for making 2D, 3D, VR and mobile games.", "gaming, game development, unity, c#, vr", 4.5),
    ("Smart Kitchen Appliances", "Connected ovens, scales and thermometers that guide recipes and cooking temperatures.", "cooking, iot, smart home, food", 3.9),
]

CATALOG = {
    "Movies": MOVIES,
    "Books": BOOKS,
    "Courses": COURSES,
    "Jobs": JOBS,
    "Apps": APPS,
    "Games": GAMES,
    "Technology": TECHNOLOGY,
}
